<div class="about-us">
<h1>Az Iroda céljai, filozófiája</h1>
<p>A tíz éves "Szimfónia" Nyugdíjas Egyesület (2013 előtt "Oltalom" Nyugdíjas Egyesület) célkitűzése a következő: olyan új kommunikációs környezet létrehozása az időskoriak számára, melyben hiteles információkhoz juthatnak. Olyan országos háló kiépítése, mely nagyrészt lefedi az ország területét, a benne lévők pedig együttműködésre törekszenek mind az Irodával, mind egymással. Az Iroda tájékoztatókat, előadásokat szervez-ajánl szakemberek segítségével a nyugdíjasokat érintő területekről. Az együttlétek kapcsán megjelenő véleményeket, igényeket, elvárásokat visszakapcsolja a mindenkori kormányzat, nyugdíjasokkal foglalkozó állami szervek (jelen esetben az Emberi Erőforrás Minisztériuma) felé, megpróbál hatással lenni ezen szervekre, hogy a hozandó intézkedések, törvények ne csak az aktuális gazdasági-politikai érdekek mentén alakuljanak, hanem figyelemmel legyenek az idősek valós vágyaira, igényeire, helyzetére és bekapcsolódást engedjenek ezen csoportnak a száraz szakmai munkába.</p>
<p>Az Iroda arra kíván törekedni, hogy az idősek társadalmával kapcsolatos hiteles információk eljussanak az apró „sejtekbe” is, hogy az élet uralkodjék és ne a félelem, ezekben a kis sejtekben. Az Iroda szeretné elősegíteni, hogy az idősek önmagukról, önmagukért tegyenek, vállaljanak felelősséget.</p>
<p>Ahogy a társadalom egyre inkább elöregszik, egyre fontosabb, hogy ezek az elöregedett „sejtek” új impulzusokat kapjanak, hogy az öregkor ne leépülés legyen, hanem egy új világ építése az idős ember tapasztalata alapján.</p>
<hr>
<p>A célkitűzéseket az Iroda a "Szimfónia" Nyugdíjas Egyesület 10 éves működésének tapasztalataira, és e tapasztalatok alapján kialakult filozófiájára alapozza.</p>
<p>Az Egyesületben lévő idősek mennyiségi együttléte átalakult minőségi kapcsolatokká. A tudatosan kialakított térben, ma már nem az önszerveződés a lényeg, hanem egy újfajta tevékenységi mód: életükben a hangsúly az önmagunkról–önmagunkért, a másokkal–másokért vállalt felelősségre tevődött. <em>„Nem a rólunk való gondoskodás, hanem hogy mi gondoskodjunk másokért.”</em></p>
<p>Régi-új szemléletmód: az időseket visszavezetni a családi gondoskodás légkörébe, hogy újból a nagycsalád vegye szárnyai alá e törékeny embereket. Ezt a megújult szemléletet és ezzel a szemlélettel eltöltött idő tapasztalatait szeretné az Iroda átadni azoknak, akik együttműködésre kívánnak lépni vele.</p>
<p>A nyugdíjas kérdést régóta szociális kérdésként kezelik. E szociális kérdés mára társadalmi kapcsolatok és függőségek hálózatává lett. De rá kell ébrednünk, hogy a nyugdíjas korosztály nem szociális kérdés, az időseket be kell vonni e szociális kérdésnek tekintett helyzet megoldásába. Az Iroda úgy látja, hogy szükséges minden erő, kapcsolat, párbeszéd mindenkivel, aki hajlandó az idősekkel, az idősek szolgálatában tenni valamit is, legyen az egyház, vállalkozó, civil szervezet vagy magán személy.</p>
<p>Ebben a munkában megrendült alázatra és korlátlan odaadásra van szükség. Az öregkor hozza meg az aratást, begyűjtését annak, amit az ember tanult és átélt, teljesített és elért, végigszenvedett és kiállt. Az idős emberben fel kell kelteni az éberséget, a gondoskodást, az önuralmat, hisz őket is könnyen megtámadja és tönkreteszi a lustaság, a változékony hangulat, a felületesség és az elkeseredettség. Újra bátorságot kell önteni beléjük, hogy társadalmunk erőforrásaivá váljanak.</p>
<hr>
<p>Az Iroda mindazokkal, akik hajlandóak az idősekkel, az idősek szolgálatában együttműködni vele, újszerű kommunikációs környezet létrehozása törekszik az idősek társadalmában.</p>
<p>A gyors iramú kommunikáció, amit magában rejt az internet, telefon, skype, nem kedvez a társadalom párbeszédszerű kapcsolatainak, az oda-vissza kapcsolat tökéletlen benne. Hiányzik belőle az emberi személy jelenszerűsége. Ha nincs megfelelő kommunikáció vagy figyelem egymás felé, akkor felveszünk egy rossz tömegviselkedési formát, amit egy torz hang könnyen irányíthat.</p>
<p>Hozzunk tehát létre olyan komfortzónát, ahol adottak a feltételek, hogy egymással és egymásért legyünk. Az összetartozás tudata, igénye, felelőssége, nemegyszer kínja sosem volt olyan erős az emberekben (köztük az időstársadalomban), mint éppen ma. Ezért a kommunikációs környezetet az időstársadalom legkisebb szintjén kell koordinálni. E remélhetőleg megújuló közösségeket szeretnénk hazánk vérkeringésében bekapcsolni.</p>
<p>A nemzedékek közötti párbeszéd az együtt cselekvés elengedhetetlen oszlopa. Az idősek időnként tehermentesítik a fiatalokat, akik ez által (is) könnyebben eltalálnak hozzájuk problémáikkal. Az öregek tapasztalata, bölcsessége jó tanáccsal, példával, tettekkel jelen van az élet sok területén, akár a családban, a közösségben, az egyesületben vagy intézményben. Az öregkor megérdemli a tiszteletet. Az idős ember: alkalom a világ számára, hogy szolgálata révén megadják számára a méltóságot, a másik ember szívében élő jó meggyőződéses tudatában.</p>
<p>Az Iroda segítő törekvése az, hogy az idősek önmaguk, az idősebb nemzedék javáért, testük, kedélyük ápolásáért, a teljes értékű életért fáradozzanak és így állandó otthonra találjanak a társadalomban, – a társadalom öregekért való munkája pedig mindinkább az öregekkel folytatott munkává váljék.</p>
<hr>
<p>Az Iroda munkája, működése. Központi, budapesti székhelyéről kapcsolatteremtésre törekszik nagyvárosokban és ezek vonzáskörzetében lévő (bármi féle) nyugdíjas szerveződésekkel. E városok: Budapest, Békéscsaba, Kaposvár, Salgótartján, Szekszárd, Székesfehérvár, Zalaegerszeg, Esztergom, Szeged, Szolnok, Eger, Szombathely, Veszprém, Pécs, Baja, Győr, Debrecen, Nyíregyháza, Miskolc. E városokban helyi (nyugdíjas) összekötőket keres meg, akik szívesen veszik fel és koordinálják a kapcsolatot az Iroda és a helyi közösségek között. E képviselők tájékoztatják a helyi szervezeteket, egyesületeket, az Iroda tervezett programjairól, illetve javaslatot tesznek a helyi igények alapján az Irodának programok szervezésére. A képviselőket az Iroda technikai eszközzel (számítógép) segíti, valamint időről-időre tájékoztató képzésekben részesíti és tevékenységüket monitorozza. Az összekötők szervezik, segítik ismereteikkel megszervezni az Iroda által finanszírozott, a körzetében megrendezésre kerülő ingyenes tájékoztatókat, előadásokat, programokat.</p>
<p>Az összekötői feladat teljesen önkéntes és térítésmentes. Ugyancsak önkéntes az együttműködés az Iroda és a nyugdíjas szervezetek között. Az önkéntesség mellett azonban az alábbi feltételekhez kötött, amelyek az Szimfónia Irodára is kötelezőek. Ezen feltétel egyben az új kommunikációs környezet létrehozásának is feltételei.</p>

<p>Az öregkor olyan, mint a szimfónia zárótétele: az élet nagy témái egy hatalmas harmóniába torkollanak. A szimfónia görög szó, ami együtthangzást jelent, sok hangszer egyetlen melódiát ad. Az Iroda szeretné összegyűjteni azokat a „hangszereket” akik ezt a csodálatos melódiát adják, melyet bölcsességnek nevezünk.</p>

<p>Budapest, 2013. január</p>

</div>